
USE_TEST_INPUT = False
DEBUG_PRINT = True
VERBOSE = False

# PROBLEM PARAMETERS
# SEARCH_LIMIT_HIGH = 100000
# SEARCH_LIMIT_LOW = 0
TOTAL_DISKSPACE = 70000000
MAX_DISK_USAGE = TOTAL_DISKSPACE - 30000000

# LIST OF COMMAND-LINE TOKENS
PROMPT = "$"
CHG_DIR = "cd"
LIST_DIR = "ls"
DIR_MARKER = "dir"
ROOT = "/"
BACK = ".."

# PRINTING CONSTANTS
INDENT = "  "