
USE_TEST_INPUT = False
DEBUG_PRINT = True
VERBOSE = False

# PROBLEM PARAMETERS
FILESIZE_LIMIT = 100000

# LIST OF COMMAND-LINE TOKENS
PROMPT = "$"
CHG_DIR = "cd"
LIST_DIR = "ls"
DIR_MARKER = "dir"
ROOT = "/"
BACK = ".."

# PRINTING CONSTANTS
INDENT = "  "