USE_TEST_INPUT = False
DEBUG_PRINT = True
VERBOSE = False

BOX_OPEN_BRACKET = "["
BOX_CLOSE_BRACKET = "]"
INPUT_SECTIONS_DELIM = "\n\n"
INPUT_STACK_EMPTY_COL_DELIM = "    "
INPUT_STACK_COLUMNS_DELIM = " "
INPUT_STACK_ROWS_DELIM = "\n"
INSTRUCTION_MOVE = "move"
INSTRUCTION_SOURCE = "from"
INSTRUCTION_TARGET = "to"
INSTRUCTION_WORDS_DELIM = " "
INSTRUCTION_LINES_DELIM = "\n"
